services:
  rest-server:
    container_name: rest-server
    build:
      context: .
      dockerfile: ./deployment/rest_server/Dockerfile
    image: rest-server:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/src/logs
    networks:
      - demo_network

    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./deployment/nginx/Dockerfile
    restart: unless-stopped
    ports:

      - "80:80"
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx
    networks:
      - demo_network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  demo_network:
